#!/usr/bin/env bash
# tests/test-orchestrating-swarms.sh — integration test for the swarm collection contract
#
# Per Fowler critique #4 closure (TICKET-025 / ADR-0030): tests the CONTRACT
# that Step 5 of `.claude/skills/orchestrating-swarms/SKILL.md` operationalizes
# — namely: "lead agent collects N worker manifests + validates each + detects
# drift per worker." Does NOT test git worktree spawning (git's responsibility)
# or Claude Code Task tool sub-agent spawn (Claude Code's responsibility);
# those have their own coverage and are explicitly out of scope per ADR-0030
# §Decision-2 (honest scope statement).
#
# Setup: synthesize 3 fake worker outputs (TICKET-SWARM-001..003) with
# non-overlapping file_scope; each gets a .req.json + .res.json + trail.
# Lead-agent role (this test): walks N workers, emits a manifest per worker,
# validates each via audit-manifest.sh, verifies --regenerate drift detection.
#
# Cleanup: restore-before-assert pattern; all synthesized artifacts removed
# regardless of test outcome.

set -u
QUIET=0
for arg in "$@"; do [ "$arg" = "--quiet" ] && QUIET=1; done
log() { [ "$QUIET" -eq 0 ] && printf '%s\n' "$*"; return 0; }
log "[test-orchestrating-swarms] starting"

failures=0; passes=0
assert_eq() {
    if [ "$1" = "$2" ]; then log "  ✓ $3"; passes=$((passes+1))
    else log "  ✗ $3 (expected $2, got $1)"; failures=$((failures+1)); fi
}

# --- Fixture: synthesize 3 worker artifact sets -----------------------------
WORKERS="TICKET-SWARM-001 TICKET-SWARM-002 TICKET-SWARM-003"
mkdir -p .harness/handoffs .harness/trails .harness/audit

synth_worker() {
    local id="$1" scope_path="$2"
    cat > ".harness/handoffs/${id}.req.json" <<EOF
{
  "schema_version": "1",
  "ticket_id": "${id}",
  "issued_at": "2026-05-26T20:00:00Z",
  "issued_by": "test-orchestrating-swarms",
  "acceptance_criteria": [{"id": "ac-1", "description": "synth"}],
  "file_scope": {"may_edit": ["${scope_path}"], "may_read": ["${scope_path}"]},
  "context": {"research_refs": []},
  "quality_gate": {"tests_must_pass": true, "coverage_delta_min": 0, "lint_clean": true, "provenance_complete": true}
}
EOF
    cat > ".harness/handoffs/${id}.res.json" <<EOF
{
  "schema_version": "1",
  "ticket_id": "${id}",
  "completed_at": "2026-05-26T20:01:00Z",
  "status": "green",
  "changed_files": ["${scope_path}"],
  "test_results": {"framework": "synth", "passed": 1, "failed": 0, "skipped": 0},
  "decision_trail_ref": ".harness/trails/${id}.md",
  "gate_results": {"tests_must_pass": "pass", "coverage_delta_min": "pass", "lint_clean": "pass", "provenance_complete": "pass"}
}
EOF
    cat > ".harness/trails/${id}.md" <<EOF
# Decision Trail — ${id}

**Mode:** synth (tests/test-orchestrating-swarms.sh)
**Completed:** 2026-05-26T20:01:00Z

## R-G-R cycle
- **Red:** synthesized for swarm collection contract test.
- **Green:** synthesized.
- **Refactor:** None — synth.

## Files touched
- ${scope_path}

## Provenance
Generated by tests/test-orchestrating-swarms.sh for the per-worker manifest collection contract test.
EOF
}

cleanup() {
    for w in $WORKERS; do
        rm -f ".harness/handoffs/${w}.req.json" \
              ".harness/handoffs/${w}.res.json" \
              ".harness/trails/${w}.md" \
              ".harness/audit/${w}.manifest.json" \
              ".harness/audit/${w}.manifest.regenerated.json"
    done
}
trap cleanup EXIT INT TERM

# --- Setup: 3 workers with non-overlapping file_scope per G-8 ---------------
synth_worker "TICKET-SWARM-001" "examples/string-utils/src/feature-001.mjs"
synth_worker "TICKET-SWARM-002" "examples/string-utils/src/feature-002.mjs"
synth_worker "TICKET-SWARM-003" "examples/string-utils/src/feature-003.mjs"

# --- Lead-agent Step 5a: emit manifest per worker ---------------------------
for w in $WORKERS; do
    ./scripts/emit-manifest.sh --ticket "$w" --driver swarm-lead-synthesis --quiet
    exit_code=$?
    assert_eq "$exit_code" "0" "emit-manifest exits 0 for $w"
    [ -f ".harness/audit/${w}.manifest.json" ] && { log "  ✓ manifest written for $w"; passes=$((passes+1)); } \
                                                || { log "  ✗ manifest missing for $w"; failures=$((failures+1)); }
done

# --- Lead-agent Step 5b: validate each manifest via audit-manifest.sh -------
./scripts/audit-manifest.sh --quiet >/dev/null 2>&1
assert_eq "$?" "0" "audit-manifest passes all worker manifests (3+ in audit dir)"

# --- Lead-agent Step 5c: --regenerate confirms no drift for each worker ----
for w in $WORKERS; do
    ./scripts/emit-manifest.sh --ticket "$w" --regenerate --driver swarm-lead-synthesis --quiet
    assert_eq "$?" "0" "--regenerate on clean $w manifest exits 0"
done

# --- Lead-agent Step 5d: verify each worker's status was correctly indexed --
for w in $WORKERS; do
    status=$(node -e '
        const m = JSON.parse(require("fs").readFileSync(".harness/audit/" + process.env.TID + ".manifest.json", "utf8"));
        process.stdout.write(m.status);
    ' 2>/dev/null </dev/null TID="$w" || env TID="$w" node -e '
        const m = JSON.parse(require("fs").readFileSync(".harness/audit/" + process.env.TID + ".manifest.json", "utf8"));
        process.stdout.write(m.status);
    ' 2>/dev/null)
    assert_eq "$status" "green" "$w manifest status = green"
done

# --- Lead-agent Step 5e: tamper detection per-worker ------------------------
# Tamper with worker 002's trail; --regenerate must exit 1 (drift detected);
# other workers' --regenerate must still exit 0 (no cross-contamination).
printf '\n# SWARM TAMPER TEST\n' >> .harness/trails/TICKET-SWARM-002.md

./scripts/emit-manifest.sh --ticket "TICKET-SWARM-001" --regenerate --quiet >/dev/null 2>&1
assert_eq "$?" "0" "worker 001 --regenerate clean (no cross-contamination from 002 tamper)"

./scripts/emit-manifest.sh --ticket "TICKET-SWARM-002" --regenerate --quiet >/dev/null 2>&1
assert_eq "$?" "1" "worker 002 --regenerate exits 1 (drift detected after trail tamper)"

./scripts/emit-manifest.sh --ticket "TICKET-SWARM-003" --regenerate --quiet >/dev/null 2>&1
assert_eq "$?" "0" "worker 003 --regenerate clean (no cross-contamination from 002 tamper)"

# --- Lead-agent Step 5f: each worker's manifest has correct source-count ----
for w in $WORKERS; do
    source_count=$(node -e '
        const fs = require("fs");
        const m = JSON.parse(fs.readFileSync(".harness/audit/" + process.env.TID + ".manifest.json", "utf8"));
        process.stdout.write(String(m.sources.length));
    ' 2>/dev/null <<< "" )
    # Re-run in subshell with env var to set TID portably
    source_count=$(env TID="$w" node -e '
        const fs = require("fs");
        const m = JSON.parse(fs.readFileSync(".harness/audit/" + process.env.TID + ".manifest.json", "utf8"));
        process.stdout.write(String(m.sources.length));
    ' 2>/dev/null)
    assert_eq "$source_count" "3" "$w manifest has 3 sources (request + response + trail)"
done

# --- Report -----------------------------------------------------------------
total=$((passes + failures))
if [ "$failures" -eq 0 ]; then
    log "[test-orchestrating-swarms] OK — $passes/$total passed (collection contract verified for 3 workers)."
    exit 0
else
    log "[test-orchestrating-swarms] FAIL — $failures/$total failures."
    exit 1
fi
