#!/usr/bin/env bash
# scripts/export-cursor-rules.sh — generate .cursor/rules/*.mdc from sources-of-truth
#
# Generated outputs:
#   .cursor/rules/agent-context.mdc       always-loaded; session-start ritual + authority pointers
#   .cursor/rules/harness-overview.mdc    agent-loaded; two-tier outer/inner loop summary
#   .cursor/rules/quality-gate.mdc        agent-loaded; sub-gates surfaced from docs/quality-gate.md
#   .cursor/rules/d-rules.mdc             agent-loaded; D-1..D-13 headers parsed from
#                                         docs/founder-directives.md §3 (headers only per D-6)
#
# Cursor lacks Claude Code's push-hook mechanism; .cursor/rules/*.mdc with
# alwaysApply: true is the always-loaded equivalent for agent-context.
# Per ADR-0014, these files are generator-output-only; hand-edits are caught
# by scripts/audit-doc-drift.sh F-5.
#
# Usage:
#   scripts/export-cursor-rules.sh                # default: write to .cursor/rules/
#   scripts/export-cursor-rules.sh --check        # write to temp; diff vs .cursor/rules/; exit 1 if drift
#   scripts/export-cursor-rules.sh --quiet        # suppress per-file status output
#
# Exit codes:
#   0  success (write mode: files written; check mode: no drift)
#   1  --check found drift between on-disk and freshly-generated output
#   2  error (missing source-of-truth, mktemp failure, write failure)
#
# Portability target: bash 3.2 + BSD coreutils (per C-23, validated against
# tdd-pro-bash32-portability's 9 gotchas).

set -u

MODE="write"
QUIET=0
for arg in "$@"; do
    case "$arg" in
        --check) MODE="check" ;;
        --write) MODE="write" ;;
        --quiet) QUIET=1 ;;
        -h|--help)
            sed -n '2,28p' "$0" | sed 's/^# \{0,1\}//' >&2
            exit 0
            ;;
        *)
            printf 'export-cursor-rules.sh: unknown arg: %s\n' "$arg" >&2
            exit 2
            ;;
    esac
done

log() {
    if [ "$QUIET" -eq 0 ]; then
        printf '%s\n' "$*"
    fi
}

die() {
    printf 'export-cursor-rules.sh: %s\n' "$*" >&2
    exit 2
}

FD_PATH="docs/founder-directives.md"
QG_PATH="docs/quality-gate.md"

[ -f "$FD_PATH" ] || die "source-of-truth missing: $FD_PATH (run from repo root)"
[ -f "$QG_PATH" ] || die "source-of-truth missing: $QG_PATH (run from repo root)"

# Output directory: real target in write mode; temp in check mode (cleaned via trap).
if [ "$MODE" = "check" ]; then
    OUTDIR=$(mktemp -d -t cursor-rules.XXXXXX) || die "mktemp -d failed"
    trap 'rm -rf -- "$OUTDIR"' EXIT INT TERM
else
    OUTDIR=".cursor/rules"
    mkdir -p "$OUTDIR" || die "could not create $OUTDIR"
fi

# --- Generator: agent-context.mdc -------------------------------------------

gen_agent_context() {
    cat <<'EOF'
---
description: grok-claude-tdd-pro harness — session-start ritual + authority pointers (always-loaded)
alwaysApply: true
---

# Generated by scripts/export-cursor-rules.sh — DO NOT EDIT
#
# Hand-edits will be caught by scripts/audit-doc-drift.sh F-5.
# To change content, edit the generator (scripts/export-cursor-rules.sh) and re-run.

# Harness session-start context (always-loaded)

**If the operator is bootstrapping the harness or asks "how do I start", route them to `QUICKSTART.md` at repo root.** It's the operator entry point: 3-minute environment bootstrap + 15-minute first cycle + 7 daily slash commands + common gotchas. This rule file is your binding context for what to do on every action; QUICKSTART is what the operator reads first.

Before ANY action in this repo:

1. Run `./scripts/sync-plugin.sh --ensure` in the terminal. This materializes the pinned plugin commit at `.harness/plugin-cache/claude-tdd-pro/` and validates the `.claude/skills/tdd-pro-*` symlinks. Without it, the inner-loop SKILL.md files will not resolve.
2. Read `AGENTS.md` at repo root for the full cross-tool surface enumeration.

Authority hierarchy (full text in `AGENTS.md §5` + `CLAUDE.md`):

- TIER 0: `docs/ai-engineering-corpus.md` — supreme operating directive.
- TIER 1: `CLAUDE.md` (prime directive: plugin-dependency model) + `docs/founder-directives.md` (D-1..D-13).
- TIER 2: `docs/architecture-principles.md` (R-1..R-20), `docs/grok-orchestration-principles.md` (G-1..G-21), `docs/claude-tdd-pro-principles.md` (C-1..C-24), `docs/quality-gate.md`, `docs/self-healing-design.md`, `docs/handoff-contract.md`, `docs/cursor-integration.md`, `docs/provenance-bridging-design.md`, `docs/researcher-discipline.md`.

Inner-loop skills (read BEFORE writing any spec, substrate, or commit):

- `.claude/skills/tdd-pro-cl-workflow/SKILL.md` — per-CL Red-Green-Refactor discipline.
- `.claude/skills/tdd-pro-batch-cl/SKILL.md` — substrate-touch CL batching convention.
- `.claude/skills/tdd-pro-bash32-portability/SKILL.md` — bash 3.2 + BSD portability checklist (read before any new `.sh` edit).

Outer-loop templates (read when the operator invokes research / decomposition / dispatch):

- `.grok/templates/research.md`
- `.grok/templates/decomposition.md`
- `.grok/templates/dispatch.md`

File-edit fences (full list in `AGENTS.md §2`): do NOT edit `.harness/plugin-cache/`, `claude-tdd-pro/`, `.claude/skills/tdd-pro-*` symlinks, `docs/founder-directives.md §1` (immutable), `docs/founder-directives.md §3` D-rule bodies, or `.cursor/rules/*.mdc` (these files — generator output).

Pre-commit gate: `./scripts/audit-doc-drift.sh` MUST exit 0 before commit. Walk `docs/founder-directives.md §4` D-checklist (D-1..D-13 + D-1 reverse from ADR-0013 + Q-DOC-DRIFT) and apply the TIER-0 corpus checklist first.

D-1 reverse attribution per ADR-0013: this Cursor-side always-loaded rule mirrors the intent of `.claude/hooks/session-start.sh` (Claude Code's push-hook); Cursor lacks a push-hook mechanism, so the always-loaded rule is the equivalent surface per ADR-0014.
EOF
}

# --- Generator: harness-overview.mdc ----------------------------------------

gen_harness_overview() {
    cat <<'EOF'
---
description: grok-claude-tdd-pro two-tier loop summary (outer Grok + inner Claude TDD Pro)
alwaysApply: false
---

# Generated by scripts/export-cursor-rules.sh — DO NOT EDIT
#
# Hand-edits will be caught by scripts/audit-doc-drift.sh F-5.

# Harness overview

Two-tier loop:

**Outer loop (Grok-orchestrated; template-driven, not code-driven):**

- `.grok/templates/research.md` — produce `research_refs` for a topic.
- `.grok/templates/decomposition.md` — turn research into atomic, contract-shaped tickets.
- `.grok/templates/dispatch.md` — emit a contract-valid `.harness/handoffs/TICKET-NNN.req.json` for one ticket per `docs/handoff-contract.md §Grok→Claude`.

**Inner loop (Claude-TDD-Pro-skilled; R-G-R per ticket):**

- Driver: Cursor's chat agent (primary, in-process) OR headless `claude -p` (alternative, separate process). See `docs/cursor-integration.md §§4-5`.
- Discipline: `.claude/skills/tdd-pro-cl-workflow/SKILL.md` Red-Green-Refactor sequence.
- Output: `.harness/handoffs/TICKET-NNN.res.json` per `docs/handoff-contract.md §Claude→Grok` + `.harness/trails/TICKET-NNN.md` decision trail.

**Handoff (the wire between outer and inner):**

- Format: `.harness/handoffs/TICKET-NNN.{req,res}.json`, `schema_version: "1"`.
- Schemas: `docs/handoff-contract.md §Grok→Claude` (request), `§Claude→Grok` (response).

**Quality gate (applied at diff review):**

- Four sub-gates per `docs/quality-gate.md`: `tests_must_pass`, `coverage_delta_min`, `lint_clean`, `provenance_complete` (recommended at v1; required at v2).
- See `.cursor/rules/quality-gate.mdc` for IDE-consumable form.

**Long-loop self-healing (design only at v1; implementation deferred):**

- Design: `docs/self-healing-design.md`. Implementation deferred per ADR-0011.

D-1 reverse attribution per ADR-0013: this Cursor-side overview's Grok analog is `docs/grok-orchestration-principles.md`; this file is a UI-consumable summary that surfaces the same two-tier model to Cursor's chat agent.
EOF
}

# --- Generator: quality-gate.mdc --------------------------------------------

gen_quality_gate() {
    cat <<'EOF'
---
description: grok-claude-tdd-pro quality-gate sub-gates (enforce when reviewing inner-loop diffs)
alwaysApply: false
---

# Generated by scripts/export-cursor-rules.sh — DO NOT EDIT
#
# Sub-gate definitions live in docs/quality-gate.md (single source of truth, R-3).
# This file surfaces them in IDE-consumable form so Cursor's chat agent enforces
# at diff review. Hand-edits caught by scripts/audit-doc-drift.sh F-5.

# Quality gate (enforce at diff review)

When reviewing a diff produced by `/inner-loop` (or any inner-loop invocation), confirm each sub-gate per `docs/quality-gate.md`.

## Sub-gate 1: `tests_must_pass` (REQUIRED)

- All tests in the changed `file_scope` and their direct dependents pass (`status: green`).
- No per-CL override.
- Source-of-truth: `docs/quality-gate.md §Sub-gate 1: tests_must_pass`.

## Sub-gate 2: `coverage_delta_min` (REQUIRED, default 0)

- Coverage on changed files does not decrease by more than the configured `coverage_delta_min` (default 0 — no decrease allowed).
- Per-CL override allowed with documented rationale in the `.res.json` `gate_results` or commit body.
- Source-of-truth: `docs/quality-gate.md §Sub-gate 2: coverage_delta_min`.

## Sub-gate 3: `lint_clean` (REQUIRED)

- No new lint warnings or errors in changed `file_scope`.
- Per-CL override allowed with documented rationale.
- Source-of-truth: `docs/quality-gate.md §Sub-gate 3: lint_clean`.

## Sub-gate 4: `provenance_complete` (REQUIRED post-TICKET-010 trilogy; ADR-0026)

- Decision trail at `.harness/trails/TICKET-NNN.md` names the R-G-R steps (or skip rationale per SKILL.md's allowance for stub-shape commits).
- Manifest at `.harness/audit/TICKET-NNN.manifest.json` exists, validates per `scripts/audit-manifest.sh` (ADR-0020), and `scripts/emit-manifest.sh --regenerate` shows no source-sha drift (ADR-0021).
- Promotion mechanism: the TICKET-010 trilogy (010.a/.b/.c) provides the structural enforcement bar; promotion to REQUIRED landed via ADR-0026 WITHOUT a `schema_version` bump (wire-format compatibility preserved per R-11).
- Borrows from plugin `architecture-v1.9.md §2.8 AI Provenance Manifest`.
- Source-of-truth: `docs/quality-gate.md §Sub-gate 4: provenance_complete`.

## Cross-cutting checks

- Diff stays within the ticket's `file_scope` per `.req.json`.
- `.req.json` and `.res.json` are `schema_version: "1"`.
- See `docs/quality-gate.md §Cross-cutting checks` for the full list.

D-1 reverse attribution per ADR-0013: the quality-gate sub-gates are harness-native (cross-tool quality contract; no Cursor / Claude / Grok analog to cite).
EOF
}

# --- Generator: d-rules.mdc (parses §3 headers from founder-directives.md) --

gen_d_rules() {
    cat <<'EOF'
---
description: grok-claude-tdd-pro founder-directives D-1..D-13 catalog (canonical bodies in docs/founder-directives.md §3)
alwaysApply: false
---

# Generated by scripts/export-cursor-rules.sh — DO NOT EDIT
#
# Headers parsed from docs/founder-directives.md §3 (per D-6, the §3 D-rule
# bodies are TIER 1 amendable-only-via-ADR; this file surfaces the catalog
# only). Hand-edits caught by scripts/audit-doc-drift.sh F-5.

# Founder-directives catalog (D-1..D-13)

Headers only. For canonical D-rule bodies (immutable-via-ADR per D-6), read `docs/founder-directives.md §3`.

EOF
    awk '
        /^### D-[0-9]+ / {
            sub(/^### /, "", $0);
            n = index($0, " — ");
            if (n > 0) {
                printf "- **%s**%s\n", substr($0, 1, n-1), substr($0, n);
            } else {
                printf "- **%s**\n", $0;
            }
        }
    ' "$FD_PATH"

    cat <<'EOF'

Pre-commit: walk `docs/founder-directives.md §4` D-checklist (D-1..D-13 + the D-1 reverse item from ADR-0013 + Q-DOC-DRIFT). Document any unmet directive in the commit body.

D-1 reverse attribution per ADR-0013: this catalog has no Grok analog (the D-rules ARE the cross-tool founder-directives surface); this file gives Cursor's chat agent quick reference vs. requiring it to grep §3 on every session.
EOF
}

# --- Write or check ---------------------------------------------------------

OUTPUTS="agent-context.mdc harness-overview.mdc quality-gate.mdc d-rules.mdc"
status=0

for out in $OUTPUTS; do
    target="$OUTDIR/$out"
    case "$out" in
        agent-context.mdc)    gen_agent_context    > "$target" ;;
        harness-overview.mdc) gen_harness_overview > "$target" ;;
        quality-gate.mdc)     gen_quality_gate     > "$target" ;;
        d-rules.mdc)          gen_d_rules          > "$target" ;;
    esac
    if [ "$MODE" = "check" ]; then
        on_disk=".cursor/rules/$out"
        if [ ! -f "$on_disk" ]; then
            log "[cursor-rules] MISSING on disk: $on_disk (run scripts/export-cursor-rules.sh)"
            status=1
        elif ! diff -q -- "$target" "$on_disk" >/dev/null 2>&1; then
            log "[cursor-rules] DRIFT: $on_disk differs from generator output"
            log "  (run scripts/export-cursor-rules.sh to regenerate)"
            status=1
        fi
    else
        log "[cursor-rules] wrote $target"
    fi
done

if [ "$MODE" = "check" ] && [ "$status" -eq 0 ]; then
    log "[cursor-rules] OK — all .cursor/rules/*.mdc match generator output."
fi

exit $status
